name: "New Video"
description: "Publish a YouTube video"
labels: ["video"]
body:
  - type: dropdown
    id: world
    attributes:
      label: World
      options:
        - tech
        - film
        - music
        - writing
        - travel
    validations:
      required: true
  - type: input
    id: url
    attributes:
      label: YouTube URL
      placeholder: "https://youtube.com/watch?v=..."
    validations:
      required: true
  - type: input
    id: description
    attributes:
      label: Description
  - type: input
    id: tags
    attributes:
      label: Tags
      description: "Comma-separated"
      placeholder: "travel, vlog"
